# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Main CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
        dir: 'client'
    - name: Run test in sub-folder
      uses: borales/actions-yarn@v4
      with:
        cmd: test
        dir: 'client' # will run `yarn test` in `client` sub folder
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: 'client'
    - name: Deploy to Github Pages
      uses: borales/actions-yarn@v4
      with:
        cmd: deploy
        dir: 'client'
